CREATE TABLE IF NOT EXISTS game_saves(user_id TEXT PRIMARY KEY,save_data TEXT NOT NULL,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS rankings(user_id TEXT PRIMARY KEY,score INTEGER NOT NULL DEFAULT 0,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT,nickname TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);