name = "komsco-3d"
main = "src/worker.js"
compatibility_date = "2026-07-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "komsco-3d"
database_id = "0e2e6b84-54be-4cf2-af3b-e544dfc35a7a"
