import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';

const $=id=>document.getElementById(id);
const MOBILE=matchMedia('(max-width:780px)').matches;
const DEVICE_LOW=(navigator.deviceMemory&&navigator.deviceMemory<=4)||MOBILE;
const DEFAULT={coin:100,xp:0,done:{},inventory:{},plots:Array.from({length:12},()=>null),avatar:null,quality:DEVICE_LOW?'low':'high',costume:{tint:'#ffffff',hat:'none'},sound:true,tutorialDone:false};
let state={...DEFAULT,...safeJSON(localStorage.getItem('komscoFarm3D'))};
if(!Array.isArray(state.plots)||state.plots.length!==12)state.plots=Array.from({length:12},()=>null);
function safeJSON(v){try{return JSON.parse(v||'{}')}catch{return {}}}
const save=()=>{localStorage.setItem('komscoFarm3D',JSON.stringify(state));syncCloud()};

let scene,camera,renderer,clock,player,playerVisual,selectedAvatar,nearPOI=null,cameraYaw=.75,cameraPitch=.52;
let move={x:0,z:0},velocity=new THREE.Vector3(),keys={},dragging=false,lastPointer={x:0,y:0},runHeld=false,elapsed=0;
const mixers=[],waterMats=[],pois=[],colliders=[],farmBeds=[],models=new Map(),previewRenderers=[];
const loader=new GLTFLoader(),draco=new DRACOLoader();draco.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.7/');loader.setDRACOLoader(draco);
const MODEL={hunmin:'hunmin.glb',daim:'daim.glb',sunsik:'sunsik.glb',headquarters:'headquarters.glb',paper:'paper_hq.glb',currency:'currency_hq.glb',id:'id_hq.glb',rnd:'research_institute.glb',tree1:'tree_broadleaf.glb',tree2:'tree_conifer.glb',tree3:'tree_pine.glb',bench:'bench.glb',lamp:'streetlamp.glb',flower:'flower_bed.glb',sign:'signboard.glb'};
const zones=[
{id:'headquarters',name:'본사',model:'headquarters',x:-35,z:26,rot:.08,reward:55,task:'친환경·중소기업 우선구매 검토'},
{id:'paper',name:'제지본부',model:'paper',x:-35,z:-27,rot:0,reward:45,task:'특수용지 생산 자재 발주'},
{id:'currency',name:'화폐본부',model:'currency',x:0,z:-44,rot:0,reward:60,task:'보안잉크·정밀부품 발주'},
{id:'id',name:'ID본부',model:'id',x:35,z:-27,rot:0,reward:50,task:'신분증 보안소재 검토'},
{id:'rnd',name:'기술연구원',model:'rnd',x:35,z:26,rot:0,reward:65,task:'연구개발 최적 대안 선정'}];
const shop={id:'shop',name:'씨앗 상점',x:-14,z:55,type:'shop'};
const farm={id:'farm',name:'주말농장',x:23,z:67,type:'farm'};
const seeds=[{id:'lettuce',name:'상추',price:20,grow:60000,reward:38,emoji:'🥬'},{id:'tomato',name:'토마토',price:35,grow:120000,reward:70,emoji:'🍅'},{id:'strawberry',name:'딸기',price:50,grow:180000,reward:110,emoji:'🍓'},{id:'sunflower',name:'해바라기',price:28,grow:90000,reward:52,emoji:'🌻'}];
const avatarInfo=[{id:'hunmin',name:'훈민',role:'균형형',desc:'업무와 농장 활동이 안정적인 캐릭터',bonus:'모든 보상 +5%'},{id:'daim',name:'다임',role:'업무형',desc:'본부 미션 보상에 특화된 캐릭터',bonus:'업무 보상 +15%'},{id:'sunsik',name:'순식',role:'농장형',desc:'빠르게 이동하며 농장을 돌보는 캐릭터',bonus:'이동속도·수확 +12%'}];
const tutorialSteps=[['이동하기','WASD·방향키 또는 왼쪽 조이스틱으로 이동합니다. 화면을 드래그하면 카메라가 회전합니다.'],['회사에서 일하기','본부 입구의 빛나는 원까지 이동한 뒤 상호작용 버튼을 누르면 업무 미션이 시작됩니다.'],['씨앗을 사고 농장 가꾸기','업무 보상으로 씨앗 상점에서 씨앗을 사고 주말농장에서 심고 수확하세요.']];

function mat(color,rough=.82,metal=.03,extra={}){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,...extra})}
function box(w,h,d,color,x=0,y=0,z=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);m.receiveShadow=true;m.castShadow=!DEVICE_LOW;return m}
function cyl(rt,rb,h,color,seg=20){const m=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,seg),mat(color));m.castShadow=!DEVICE_LOW;m.receiveShadow=true;return m}
function normalize(obj,target=8){const b=new THREE.Box3().setFromObject(obj),s=new THREE.Vector3();b.getSize(s);const scale=target/Math.max(s.x||1,s.y||1,s.z||1);obj.scale.multiplyScalar(scale);b.setFromObject(obj);obj.position.y-=b.min.y;return obj}
async function loadModel(key){if(models.has(key))return cloneSkinned(models.get(key));const url=`${import.meta.env.BASE_URL}assets/models/${MODEL[key]}`;const gltf=await loader.loadAsync(url);const base=gltf.scene;base.userData.animations=gltf.animations;base.traverse(o=>{if(o.isMesh){o.castShadow=!DEVICE_LOW;o.receiveShadow=true;o.frustumCulled=true}});models.set(key,base);return cloneSkinned(base)}
function cloneSkinned(base){const c=base.clone(true);c.userData.animations=base.userData.animations||[];return c}

async function init(){
 scene=new THREE.Scene();scene.background=new THREE.Color(0x9bd4ec);scene.fog=new THREE.FogExp2(0x9bd4ec,DEVICE_LOW?.006:.0044);
 camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,.1,320);
 renderer=new THREE.WebGLRenderer({antialias:!DEVICE_LOW,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,state.quality==='low'?1.05:1.65));renderer.shadowMap.enabled=state.quality!=='low';renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;$('app').appendChild(renderer.domElement);clock=new THREE.Clock();
 addLights();await preloadCore();await buildWorld();setupUI();animate();$('loading').classList.add('hidden');
}
function addLights(){scene.add(new THREE.HemisphereLight(0xe6f6ff,0x5a764a,2.15));const sun=new THREE.DirectionalLight(0xfff2cf,2.7);sun.position.set(-45,72,30);sun.castShadow=state.quality!=='low';sun.shadow.mapSize.set(state.quality==='low'?512:1536,state.quality==='low'?512:1536);sun.shadow.camera.left=-95;sun.shadow.camera.right=95;sun.shadow.camera.top=95;sun.shadow.camera.bottom=-95;scene.add(sun);const fill=new THREE.DirectionalLight(0x8fc5ff,.55);fill.position.set(45,30,-50);scene.add(fill)}
async function preloadCore(){const keys=Object.keys(MODEL);let n=0;for(const k of keys){try{await loadModel(k)}catch(e){console.warn('모델 로드 실패',k,e)}n++;$('loadText').textContent=`3D 모델 준비 중 ${n}/${keys.length}`;$('loadFill').style.width=`${Math.round(n/keys.length*100)}%`}}

async function buildWorld(){
 scene.add(box(160,1,178,0x78a75f,0,-.55,10));addTerrainPatches();buildRiver();buildRoadNetwork();buildSidewalks();buildPlaza();buildBridges();
 for(const z of zones)await placeZone(z);placeShop();placeFarm();await scatterNature();addClouds();
}
function addTerrainPatches(){for(let i=0;i<(DEVICE_LOW?18:38);i++){const r=THREE.MathUtils.randFloat(3,9),m=new THREE.Mesh(new THREE.CircleGeometry(r,16),mat(i%3?0x70a25a:0x86b76b));m.rotation.x=-Math.PI/2;m.position.set(THREE.MathUtils.randFloatSpread(140),.015,THREE.MathUtils.randFloat(-70,88));scene.add(m)}}
function buildRiver(){const pts=[[-80,-3],[-58,-1],[-36,5],[-12,8],[12,5],[36,10],[58,17],[82,13]].map(([x,z])=>new THREE.Vector3(x,.1,z));const curve=new THREE.CatmullRomCurve3(pts);const water=new THREE.Mesh(new THREE.TubeGeometry(curve,150,5.8,18,false),new THREE.MeshPhysicalMaterial({color:0x42a8dc,roughness:.18,metalness:0,transparent:true,opacity:.88,clearcoat:.45}));water.rotation.x=Math.PI/2;water.position.y=-.35;scene.add(water);waterMats.push(water.material);for(const s of [-1,1]){const bp=pts.map(p=>new THREE.Vector3(p.x,p.y,p.z+s*7.1));const b=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(bp),130,1.15,9,false),mat(0xcbb17a));b.rotation.x=Math.PI/2;b.position.y=-.18;scene.add(b)}for(let i=0;i<28;i++){const t=i/27,p=curve.getPoint(t),stone=cyl(.38,.5,.4,0xd9c495,10);stone.position.set(p.x,.05,p.z+(i%2?6.4:-6.4));stone.rotation.y=i*.7;scene.add(stone)}}
function road(x,z,w,d,rot=0){const r=box(w,.16,d,0x3f474c,x,.03,z);r.rotation.y=rot;scene.add(r);return r}
function dashLine(x,z,len,vertical=true){for(let v=-len/2+3;v<len/2;v+=7){const m=box(vertical?.14:3,.025,vertical?3:.14,0xf4cd45,vertical?x:x+v,.13,vertical?z+v:z);scene.add(m)}}
function buildRoadNetwork(){road(0,2,9,100);road(0,35,112,9);road(0,-31,112,9);road(-40,2,9,75);road(40,2,9,75);road(0,56,55,8);road(13,68,8,30);dashLine(0,2,100,true);dashLine(0,35,112,false);dashLine(0,-31,112,false);dashLine(-40,2,75,true);dashLine(40,2,75,true);const ring=new THREE.Mesh(new THREE.RingGeometry(10,15,56),mat(0x3f474c));ring.rotation.x=-Math.PI/2;ring.position.y=.12;scene.add(ring);const island=new THREE.Mesh(new THREE.CircleGeometry(9.6,48),mat(0x78a95f));island.rotation.x=-Math.PI/2;island.position.y=.13;scene.add(island)}
function buildSidewalks(){const strips=[[-6,2,2,100],[6,2,2,100],[0,29,112,2],[0,41,112,2],[-46,2,2,75],[-34,2,2,75],[34,2,2,75],[46,2,2,75],[0,51,55,2],[0,61,55,2]];for(const [x,z,w,d] of strips){scene.add(box(w,.22,d,0xc9c9c3,x,.13,z));const count=Math.floor((w>d?w:d)/3);for(let i=0;i<count;i++){const seam=box(w>d?.04:w-.2,.025,w>d?d-.2:.04,0xa9aaa7,w>d?x-w/2+1.5+i*3:x,.255,w>d?z:z-d/2+1.5+i*3);scene.add(seam)}}}
function buildPlaza(){const p=cyl(22,22,.32,0xc8c3ad,64);p.position.y=.13;scene.add(p);const f=cyl(4.8,5.2,1.2,0xd8c8a0,36);f.position.y=.65;scene.add(f);const fw=cyl(3.8,3.8,.28,0x57bde2,36);fw.position.y=1.3;scene.add(fw);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,lamp=box(.12,3,.12,0x36444a,Math.cos(a)*18,1.5,Math.sin(a)*18);scene.add(lamp);const bulb=new THREE.Mesh(new THREE.SphereGeometry(.22,10,8),mat(0xffe7a6));bulb.position.set(Math.cos(a)*18,3.05,Math.sin(a)*18);scene.add(bulb)}}
function buildBridges(){[-20,22].forEach(x=>{scene.add(box(12,.65,16,0x62696d,x,.38,6));scene.add(box(12,.55,.35,0xbec1bd,x,1,13.3));scene.add(box(12,.55,.35,0xbec1bd,x,1,-1.3));for(let i=-5;i<=5;i+=2){scene.add(box(.22,1,.22,0xbec1bd,x+i,.8,13.3));scene.add(box(.22,1,.22,0xbec1bd,x+i,.8,-1.3))}})}
async function placeZone(z){let obj;try{obj=normalize(await loadModel(z.model),13)}catch{obj=box(12,10,10,0xe8e0d0)}obj.position.set(z.x,0,z.z);obj.rotation.y=z.rot;scene.add(obj);const entrance=new THREE.Vector3(z.x,0,z.z<0?z.z+9:z.z-9);pois.push({...z,entrance});marker(z.name,entrance.x,entrance.z);interactionRing(entrance.x,entrance.z,0xefc35b);colliders.push({x:z.x,z:z.z,r:8})}
function marker(text,x,z){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d');g.fillStyle='rgba(8,28,43,.9)';g.roundRect(8,8,496,112,34);g.fill();g.strokeStyle='#efc35b';g.lineWidth=5;g.stroke();g.fillStyle='#fff7e3';g.font='900 43px Noto Sans KR,sans-serif';g.textAlign='center';g.fillText(text,256,78);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));sp.position.set(x,6.8,z);sp.scale.set(7,1.75,1);scene.add(sp)}
function interactionRing(x,z,color){const ring=new THREE.Mesh(new THREE.RingGeometry(1.7,2.15,32),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.62,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.16,z);ring.userData.pulse=true;scene.add(ring)}
function placeShop(){const b=box(12,6,10,0xefe0b6,shop.x,3,shop.z);scene.add(b);scene.add(box(12.6,.55,2,0xd96f55,shop.x,5.55,shop.z-5.3));for(let i=-4;i<=4;i+=2)scene.add(box(.75,.06,3,i%4?0xffffff:0xd96f55,shop.x+i,5.2,shop.z-5.65));marker('씨앗 상점',shop.x,shop.z-6);const entrance=new THREE.Vector3(shop.x,0,shop.z-7);pois.push({...shop,entrance});interactionRing(entrance.x,entrance.z,0x54bd7d);colliders.push({x:shop.x,z:shop.z,r:7})}
function placeFarm(){scene.add(box(31,.5,24,0x936233,farm.x,-.2,farm.z));for(let i=0;i<12;i++){const col=i%4,row=Math.floor(i/4),x=farm.x-10.5+col*7,z=farm.z-7+row*7;const bed=box(5.4,.35,4.6,0x6f4328,x,.15,z);scene.add(bed);farmBeds.push({mesh:bed,x,z,index:i,crop:null})}for(let i=-15;i<=15;i+=3){scene.add(box(.18,1,.18,0xd6bf88,farm.x+i,.5,farm.z-12));scene.add(box(.18,1,.18,0xd6bf88,farm.x+i,.5,farm.z+12))}marker('주말농장',farm.x,farm.z-13);const entrance=new THREE.Vector3(farm.x,0,farm.z-13);pois.push({...farm,entrance});interactionRing(entrance.x,entrance.z,0x54bd7d);refreshCrops()}
async function scatterNature(){const keys=['tree1','tree2','tree3'];const count=DEVICE_LOW?24:46;for(let i=0;i<count;i++){let o;try{o=normalize(await loadModel(keys[i%3]),THREE.MathUtils.randFloat(3.6,6.3))}catch{o=cyl(0,.8,3.5,0x43834b,8)}let x,z;do{x=THREE.MathUtils.randFloatSpread(145);z=THREE.MathUtils.randFloat(-68,88)}while(Math.abs(x)<49&&[-31,35].some(v=>Math.abs(z-v)<10)||Math.abs(x)<10);o.position.set(x,0,z);o.rotation.y=Math.random()*Math.PI*2;scene.add(o)}for(let i=0;i<(DEVICE_LOW?8:16);i++){const b=box(2.8,.35,.7,0x8a6138,THREE.MathUtils.randFloatSpread(90),.45,THREE.MathUtils.randFloat(18,80));scene.add(b)}}
function addClouds(){for(let i=0;i<(DEVICE_LOW?5:9);i++){const g=new THREE.Group();for(let j=0;j<5;j++){const s=new THREE.Mesh(new THREE.SphereGeometry(THREE.MathUtils.randFloat(2,4),12,8),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.72}));s.position.set(j*2.5+Math.random()*2,Math.random()*1.8,Math.random()*2);g.add(s)}g.position.set(THREE.MathUtils.randFloatSpread(150),THREE.MathUtils.randFloat(28,42),THREE.MathUtils.randFloat(-70,85));g.userData.cloudSpeed=THREE.MathUtils.randFloat(.25,.55);scene.add(g)}}

function setupUI(){renderAvatarCards();bindInput();updateUI();$('enterBtn').addEventListener('click',enterWorld);$('interactBtn').addEventListener('click',interact);$('mapBtn').addEventListener('click',openMap);$('bagBtn').addEventListener('click',openBag);$('styleBtn').addEventListener('click',openStyle);$('settingsBtn').addEventListener('click',openSettings);$('closeModal').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('questToggle').addEventListener('click',()=>{$('questPanel').classList.toggle('collapsed');$('questToggle').textContent=$('questPanel').classList.contains('collapsed')?'+':'−'});$('runBtn').addEventListener('pointerdown',()=>runHeld=true);['pointerup','pointercancel','pointerleave'].forEach(e=>$('runBtn').addEventListener(e,()=>runHeld=false));window.addEventListener('resize',resize)}
function renderAvatarCards(){const grid=$('avatarGrid');grid.innerHTML='';avatarInfo.forEach(a=>{const el=document.createElement('article');el.className='avatarCard';el.innerHTML=`<div class="avatarPreview" id="preview-${a.id}"></div><div><h3>${a.name}</h3><p>${a.desc}</p><span class="role">${a.role} · ${a.bonus}</span></div>`;el.addEventListener('click',()=>{selectedAvatar=a.id;[...grid.children].forEach(x=>x.classList.remove('sel'));el.classList.add('sel');$('enterBtn').disabled=false});grid.appendChild(el);makePreview(a.id,$(`preview-${a.id}`))})}
async function makePreview(id,host){const s=new THREE.Scene();s.background=new THREE.Color(0xb6ddec);const c=new THREE.PerspectiveCamera(32,host.clientWidth/host.clientHeight,.1,100);c.position.set(4,4.5,8);c.lookAt(0,2,0);const r=new THREE.WebGLRenderer({antialias:true,alpha:false});r.setPixelRatio(Math.min(devicePixelRatio,1.4));r.setSize(host.clientWidth,host.clientHeight);r.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(r.domElement);s.add(new THREE.HemisphereLight(0xffffff,0x68865a,2.4));try{const o=normalize(await loadModel(id),4.7);s.add(o);const tick=()=>{if(!document.body.contains(host))return;o.rotation.y+=.006;r.render(s,c);requestAnimationFrame(tick)};tick()}catch{host.textContent='모델 미리보기 준비 중'}previewRenderers.push(r)}
async function enterWorld(){state.avatar=selectedAvatar;save();$('avatarSelect').classList.add('hidden');await spawnPlayer();if(!state.tutorialDone)showTutorial()}
async function spawnPlayer(){player=new THREE.Group();player.position.set(0,0,21);scene.add(player);try{playerVisual=normalize(await loadModel(state.avatar),3.5);player.add(playerVisual);const clips=playerVisual.userData.animations||[];if(clips.length){const mixer=new THREE.AnimationMixer(playerVisual);const walk=clips.find(c=>/walk|run|idle/i.test(c.name))||clips[0];mixer.clipAction(walk).play();mixers.push(mixer);player.userData.hasAnimation=true}}catch{playerVisual=cyl(.45,.65,2.6,0xe9c38c,12);playerVisual.position.y=1.3;player.add(playerVisual)}applyCostume();camera.position.set(10,11,32);updateCamera(1)}
function applyCostume(){if(!playerVisual)return;playerVisual.traverse(o=>{if(o.isMesh&&o.material&&state.costume.tint!=='#ffffff'){o.material=o.material.clone();o.material.color.lerp(new THREE.Color(state.costume.tint),.18)}});const old=player.getObjectByName('costumeHat');if(old)player.remove(old);if(state.costume.hat!=='none'){const g=new THREE.Group();g.name='costumeHat';let h;if(state.costume.hat==='cap'){h=cyl(.52,.52,.25,0x2b72aa,20);h.position.y=3.45}else if(state.costume.hat==='straw'){h=cyl(.75,.75,.12,0xd9b55e,24);h.position.y=3.48}else{h=new THREE.Mesh(new THREE.ConeGeometry(.55,.9,18),mat(0x7c4eb0));h.position.y=3.75}g.add(h);player.add(g)}}
function showTutorial(){let i=0;$('tutorial').classList.add('show');const draw=()=>{$('tipTitle').textContent=tutorialSteps[i][0];$('tipText').textContent=tutorialSteps[i][1];$('tipNext').textContent=i===tutorialSteps.length-1?'시작하기':'다음'};draw();$('tipNext').onclick=()=>{i++;if(i>=tutorialSteps.length){$('tutorial').classList.remove('show');state.tutorialDone=true;save()}else draw()}}

function bindInput(){window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')runHeld=true;if(e.code==='KeyE')interact()});window.addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='ShiftLeft'||e.code==='ShiftRight')runHeld=false});renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastPointer={x:e.clientX,y:e.clientY}});window.addEventListener('pointermove',e=>{if(!dragging)return;cameraYaw-=(e.clientX-lastPointer.x)*.005;cameraPitch=THREE.MathUtils.clamp(cameraPitch+(e.clientY-lastPointer.y)*.004,.22,.9);lastPointer={x:e.clientX,y:e.clientY}});window.addEventListener('pointerup',()=>dragging=false);const joy=$('joy'),knob=$('knob');let jid=null;const jmove=e=>{if(e.pointerId!==jid)return;const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),len=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);move.x=Math.cos(a)*(len/42);move.z=Math.sin(a)*(len/42);knob.style.transform=`translate(${Math.cos(a)*len}px,${Math.sin(a)*len}px)`};joy.addEventListener('pointerdown',e=>{jid=e.pointerId;joy.setPointerCapture(jid);jmove(e)});joy.addEventListener('pointermove',jmove);const end=e=>{if(e.pointerId!==jid)return;jid=null;move.x=move.z=0;knob.style.transform=''};joy.addEventListener('pointerup',end);joy.addEventListener('pointercancel',end)}
function movementInput(){let x=move.x,z=move.z;if(keys.KeyA||keys.ArrowLeft)x-=1;if(keys.KeyD||keys.ArrowRight)x+=1;if(keys.KeyW||keys.ArrowUp)z-=1;if(keys.KeyS||keys.ArrowDown)z+=1;const v=new THREE.Vector2(x,z);if(v.length()>1)v.normalize();return v}
function updatePlayer(dt){if(!player)return;const inp=movementInput(),moving=inp.lengthSq()>.001,avatarSpeed=state.avatar==='sunsik'?1.12:1,speed=(runHeld?10.5:6.3)*avatarSpeed;const forward=new THREE.Vector3(Math.sin(cameraYaw),0,Math.cos(cameraYaw)),right=new THREE.Vector3(forward.z,0,-forward.x),desired=new THREE.Vector3().addScaledVector(right,inp.x).addScaledVector(forward,inp.y).multiplyScalar(speed);velocity.lerp(desired,1-Math.exp(-dt*9));const next=player.position.clone().addScaledVector(velocity,dt);next.x=THREE.MathUtils.clamp(next.x,-75,75);next.z=THREE.MathUtils.clamp(next.z,-72,87);for(const c of colliders){const dx=next.x-c.x,dz=next.z-c.z,d=Math.hypot(dx,dz);if(d<c.r){next.x=c.x+dx/d*c.r;next.z=c.z+dz/d*c.r}}player.position.copy(next);if(moving){const ang=Math.atan2(velocity.x,velocity.z);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,ang,1-Math.exp(-dt*12));if(!player.userData.hasAnimation&&playerVisual){playerVisual.position.y=Math.abs(Math.sin(elapsed*8))*.08;playerVisual.rotation.z=Math.sin(elapsed*8)*.025}}else if(playerVisual&&!player.userData.hasAnimation){playerVisual.position.y=THREE.MathUtils.lerp(playerVisual.position.y,0,.15);playerVisual.rotation.z*=.85}findNearest();updateCamera(dt)}
function updateCamera(dt){if(!player)return;const dist=13,pitchHeight=5.2+cameraPitch*7,off=new THREE.Vector3(Math.sin(cameraYaw)*dist,pitchHeight,Math.cos(cameraYaw)*dist),target=player.position.clone().add(off),look=player.position.clone().add(new THREE.Vector3(0,2.2,0));camera.position.lerp(target,1-Math.exp(-dt*7));camera.lookAt(look);$('compass').textContent=['N','E','S','W'][Math.round(((cameraYaw%(Math.PI*2))+Math.PI*2)%(Math.PI*2)/(Math.PI/2))%4]}
function findNearest(){nearPOI=null;let best=Infinity;for(const p of pois){const d=player.position.distanceTo(p.entrance);if(d<best){best=d;nearPOI=p}}$('zone').textContent=best<15?nearPOI.name:'이동 중';const prompt=$('prompt');if(best<4.6){prompt.classList.add('ready');prompt.innerHTML=`<b>${nearPOI.name}</b>에서 상호작용할 수 있습니다 <span class="distance">${best.toFixed(1)}m</span>`}else{prompt.classList.remove('ready');prompt.innerHTML=best<18?`${nearPOI.name} 방향으로 이동하세요 <span class="distance">${best.toFixed(0)}m</span>`:'WASD/조이스틱 이동 · 화면 드래그 시점 회전 · Shift 달리기'}}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;updatePlayer(dt);for(const m of mixers)m.update(dt);for(const wm of waterMats){wm.opacity=.84+Math.sin(elapsed*1.5)*.035}scene.traverse(o=>{if(o.userData.pulse){o.scale.setScalar(1+Math.sin(elapsed*2.8)*.08);o.rotation.z+=dt*.25}if(o.userData.cloudSpeed){o.position.x+=o.userData.cloudSpeed*dt;if(o.position.x>90)o.position.x=-90}});updateCropsVisual();drawMap();renderer.render(scene,camera)}

function interact(){if(!nearPOI||!player||player.position.distanceTo(nearPOI.entrance)>4.8){toast('입구의 빛나는 원까지 이동하세요.');return}if(nearPOI.type==='shop')openShop();else if(nearPOI.type==='farm')openFarm();else openMission(nearPOI)}
function openMission(z){if(state.done[z.id]){toast('오늘 완료한 업무입니다.');return}openModal(`<h1>${z.name} 업무 미션</h1><p class="lead">${z.task}</p><div class="tile"><b>간단 의사결정</b><small>예산·품질·공공가치를 함께 고려하여 가장 적절한 선택을 하세요.</small></div><button class="choice" data-answer="1">가격만 가장 낮은 업체를 즉시 선정한다</button><button class="choice" data-answer="2">품질·납기·공공구매 가치를 종합 검토한다</button><button class="choice" data-answer="3">기존 업체와 관행대로 계약한다</button>`);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(b.dataset.answer!=='2'){toast('조금 더 종합적으로 검토해보세요.');return}let reward=z.reward;if(state.avatar==='daim')reward=Math.round(reward*1.15);else if(state.avatar==='hunmin')reward=Math.round(reward*1.05);state.coin+=reward;state.xp+=25;state.done[z.id]=true;save();updateUI();closeModal();toast(`${z.name} 업무 완료 · ${reward}G 획득`)})}
function openShop(){openModal(`<h1>🌱 씨앗 상점</h1><p class="lead">업무로 획득한 골드로 씨앗을 구매하세요.</p><div class="grid">${seeds.map(s=>`<div class="tile"><b>${s.emoji} ${s.name}</b><small>성장 ${Math.round(s.grow/60000)}분 · 수확 ${s.reward}G</small><button class="choice buy" data-seed="${s.id}">${s.price}G에 구매</button></div>`).join('')}</div>`);document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>{const s=seeds.find(x=>x.id===b.dataset.seed);if(state.coin<s.price){toast('골드가 부족합니다.');return}state.coin-=s.price;state.inventory[s.id]=(state.inventory[s.id]||0)+1;save();updateUI();toast(`${s.name} 씨앗을 구매했습니다.`)})}
function openFarm(){const now=Date.now();openModal(`<h1>🌾 주말농장</h1><p class="lead">빈 밭에 씨앗을 심고, 성장 완료 후 수확하세요.</p><div class="grid">${state.plots.map((p,i)=>{if(!p)return `<div class="tile"><b>${i+1}번 밭 · 비어 있음</b><button class="choice plant" data-plot="${i}">씨앗 심기</button></div>`;const s=seeds.find(x=>x.id===p.seed),ready=now>=p.readyAt,remain=Math.max(0,p.readyAt-now);return `<div class="tile"><b>${i+1}번 밭 · ${s.emoji} ${s.name}</b><small>${ready?'수확 가능':`약 ${Math.ceil(remain/60000)}분 남음`}</small><div class="progress"><div class="bar" style="width:${Math.min(100,100-(remain/s.grow*100))}%"></div></div><button class="choice harvest" data-plot="${i}" ${ready?'':'disabled'}>${ready?'수확하기':'성장 중'}</button></div>`}).join('')}</div>`);document.querySelectorAll('.plant').forEach(b=>b.onclick=()=>chooseSeed(Number(b.dataset.plot)));document.querySelectorAll('.harvest').forEach(b=>b.onclick=()=>harvest(Number(b.dataset.plot)))}
function chooseSeed(plot){const owned=seeds.filter(s=>(state.inventory[s.id]||0)>0);if(!owned.length){toast('가방에 씨앗이 없습니다.');return}openModal(`<h1>심을 씨앗 선택</h1><div class="grid">${owned.map(s=>`<button class="choice seedPick" data-id="${s.id}">${s.emoji} ${s.name} · ${state.inventory[s.id]}개</button>`).join('')}</div>`);document.querySelectorAll('.seedPick').forEach(b=>b.onclick=async()=>{const s=seeds.find(x=>x.id===b.dataset.id),serverNow=await getServerTime();state.inventory[s.id]--;state.plots[plot]={seed:s.id,plantedAt:serverNow,readyAt:serverNow+s.grow};save();refreshCrops();openFarm();toast(`${s.name} 씨앗을 심었습니다.`)})}
function harvest(i){const p=state.plots[i];if(!p||Date.now()<p.readyAt)return;const s=seeds.find(x=>x.id===p.seed);let reward=s.reward;if(state.avatar==='sunsik')reward=Math.round(reward*1.12);else if(state.avatar==='hunmin')reward=Math.round(reward*1.05);state.coin+=reward;state.xp+=18;state.plots[i]=null;save();refreshCrops();updateUI();openFarm();toast(`${s.name} 수확 · ${reward}G 획득`)}
function refreshCrops(){farmBeds.forEach(b=>{if(b.crop){scene.remove(b.crop);b.crop=null}const p=state.plots[b.index];if(!p)return;const s=seeds.find(x=>x.id===p.seed),g=new THREE.Group();for(let j=0;j<5;j++){const stem=cyl(.08,.1,.65,0x4f964f,8);stem.position.set((j-2)*.7,.45,Math.sin(j)*.5);g.add(stem);const fruit=new THREE.Mesh(new THREE.SphereGeometry(s.id==='sunflower'?.28:.22,10,8),mat(s.id==='tomato'?0xe85b4f:s.id==='strawberry'?0xdb4455:s.id==='sunflower'?0xf2c84b:0x65b85b));fruit.position.set((j-2)*.7,.85,Math.sin(j)*.5);g.add(fruit)}g.position.set(b.x,0,b.z);scene.add(g);b.crop=g})}
function updateCropsVisual(){const now=Date.now();farmBeds.forEach(b=>{if(!b.crop)return;const p=state.plots[b.index],s=seeds.find(x=>x.id===p.seed),progress=THREE.MathUtils.clamp((now-p.plantedAt)/s.grow,.12,1);b.crop.scale.y=THREE.MathUtils.lerp(b.crop.scale.y,progress,.06);if(progress>=1)b.crop.rotation.y=Math.sin(elapsed*1.5)*.025})}

function openMap(){openModal(`<h1>🗺️ 월드 안내</h1><p class="lead">회사 업무 지구에서 골드를 벌고 북쪽 상점과 농장으로 이동하세요.</p><canvas id="bigMap" width="720" height="520" style="width:100%;border-radius:18px;background:#78a75f"></canvas>`);drawMap($('bigMap'))}
function openBag(){openModal(`<h1>🎒 가방</h1><div class="grid">${seeds.map(s=>`<div class="tile"><b>${s.emoji} ${s.name} 씨앗</b><small>${state.inventory[s.id]||0}개 보유</small></div>`).join('')}</div><h3 class="sectionTitle">게임 진행</h3><div class="tile"><b>업무 완료 ${Object.keys(state.done).length}/5</b><small>오늘의 본부 미션을 완료하면 더 많은 씨앗을 구매할 수 있습니다.</small></div>`)}
function openStyle(){openModal(`<h1>👕 코스튬 스튜디오</h1><p class="lead">아바타의 분위기를 바꾸는 경량 코스튬입니다.</p><h3 class="sectionTitle">색상 포인트</h3><div class="grid">${['#ffffff','#4b93d1','#e66d70','#62b979','#e1b959'].map(c=>`<button class="choice tint ${state.costume.tint===c?'selected':''}" data-color="${c}"><span style="display:inline-block;width:18px;height:18px;border-radius:50%;background:${c};vertical-align:middle;margin-right:8px"></span>${c}</button>`).join('')}</div><h3 class="sectionTitle">모자</h3><div class="grid">${[['none','없음'],['cap','캡'],['straw','밀짚모자'],['wizard','연구원 모자']].map(([id,n])=>`<button class="choice hat ${state.costume.hat===id?'selected':''}" data-hat="${id}">${n}</button>`).join('')}</div>`);document.querySelectorAll('.tint').forEach(b=>b.onclick=()=>{state.costume.tint=b.dataset.color;save();applyCostume();openStyle()});document.querySelectorAll('.hat').forEach(b=>b.onclick=()=>{state.costume.hat=b.dataset.hat;save();applyCostume();openStyle()})}
function openSettings(){openModal(`<h1>⚙️ 설정</h1><div class="settingRow"><div><b>그래픽 품질</b><div class="lead">변경 후 새로고침됩니다.</div></div><select id="quality"><option value="low" ${state.quality==='low'?'selected':''}>저사양</option><option value="high" ${state.quality==='high'?'selected':''}>고품질</option></select></div><div class="settingRow"><div><b>효과음</b><div class="lead">UI 효과음 사용 여부</div></div><button id="soundSwitch" class="switch ${state.sound?'on':''}"><i></i></button></div><button id="resetBtn" class="choice" style="margin-top:18px;color:#ffd0d0">저장 데이터 초기화</button>`);$('quality').onchange=e=>{state.quality=e.target.value;save();location.reload()};$('soundSwitch').onclick=()=>{state.sound=!state.sound;save();openSettings()};$('resetBtn').onclick=()=>{if(confirm('게임 데이터를 초기화할까요?')){localStorage.removeItem('komscoFarm3D');location.reload()}}}
function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show')}function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2100)}
function updateUI(){$('coin').textContent=state.coin;$('level').textContent=1+Math.floor(state.xp/100);$('farmCount').textContent=state.plots.filter(Boolean).length;$('questRows').innerHTML=zones.map(z=>`<div class="questRow ${state.done[z.id]?'done':''}"><span>${state.done[z.id]?'✓ ':''}${z.name}</span><b>${state.done[z.id]?'완료':'+'+z.reward+'G'}</b></div>`).join('')}
function drawMap(canvas=$('mapCanvas')){if(!canvas)return;const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,sx=w/170,sy=h/180;g.clearRect(0,0,w,h);g.fillStyle='#79a95f';g.fillRect(0,0,w,h);g.strokeStyle='#3d9fd6';g.lineWidth=14;g.beginPath();g.moveTo(0,h*.48);g.bezierCurveTo(w*.25,h*.34,w*.6,h*.58,w,h*.48);g.stroke();g.strokeStyle='#43494f';g.lineWidth=9;[[w*.5,h*.08,w*.5,h*.92],[w*.1,h*.35,w*.9,h*.35],[w*.1,h*.7,w*.9,h*.7],[w*.26,h*.1,w*.26,h*.78],[w*.74,h*.1,w*.74,h*.78]].forEach(a=>{g.beginPath();g.moveTo(a[0],a[1]);g.lineTo(a[2],a[3]);g.stroke()});for(const p of pois){g.fillStyle=p.type?'#f0c96a':'#fff';g.beginPath();g.arc((p.entrance.x+85)*sx,(p.entrance.z+80)*sy,4,0,Math.PI*2);g.fill()}if(player){g.fillStyle='#ff5f62';g.beginPath();g.arc((player.position.x+85)*sx,(player.position.z+80)*sy,5,0,Math.PI*2);g.fill()}}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
async function getServerTime(){try{const r=await fetch(`${import.meta.env.BASE_URL}api/time`,{cache:'no-store'});if(r.ok){const j=await r.json();return Number(j.epoch)}}catch{}return Date.now()}
async function syncCloud(){if(location.hostname.endsWith('github.io')||location.hostname==='localhost')return;try{await fetch(`${import.meta.env.BASE_URL}api/save`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:'guest-default',nickname:'게스트',characterId:state.avatar||'hunmin',gameState:state})})}catch{}}

init().catch(e=>{$('loadText').textContent='초기화 오류: '+e.message;console.error(e)});
